# Generated by Django 4.2.3 on 2023-07-17 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(help_text='Digite um item.', max_length=220, validators=[django.core.validators.MinLengthValidator(2, 'Tem que ser maior que 1 caractere!')]),
        ),
    ]
